  -- Eliminar columna antigua de imagen única                                                                                                                                                                                                                 
  ALTER TABLE trades DROP COLUMN IF EXISTS image_url;                                                                                                                                                                                                         
                                                                                                                                                                                                                                                              
  -- Crear tabla para múltiples imágenes                                                                                                                                                                                                                      
  CREATE TABLE IF NOT EXISTS trade_images (                                                                                                                                                                                                                   
      id SERIAL PRIMARY KEY,                                                                                                                                                                                                                                  
      trade_id INTEGER NOT NULL REFERENCES trades(id) ON DELETE CASCADE,                                                                                                                                                                                      
      filename VARCHAR(255) NOT NULL,                                                                                                                                                                                                                         
      original_name VARCHAR(255),                                                                                                                                                                                                                             
      file_size INTEGER,                                                                                                                                                                                                                                      
      mime_type VARCHAR(100),                                                                                                                                                                                                                                 
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                                                                                                                                                                                                          
  );                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                              
  -- Índice para optimizar consultas por trade                                                                                                                                                                                                                
  CREATE INDEX IF NOT EXISTS idx_trade_images_trade_id ON trade_images(trade_id); 